CO2濃度の7セグLEDへの表示に対応した
realglobe-Inc/co2mon pull request #23
Opened 2020-09-02 06:49 UTC by urib0

2020-09-05 00:31 UTC, miminashi requested changes

2020-09-05 00:31 UTC, miminashi commented on app/cm-update-7seg.service
> +Description=co2mon beacon sending service
Descriptionが `co2mon beacon sending service` のままになっています。

2020-09-11 01:36 UTC, urib0 commented on app/cm-update-7seg.service
> +Description=co2mon beacon sending service
修正しました！！
- Description=co2mon beacon sending service
+ Description=co2mon 7seg updating service

2020-09-12 00:08 UTC, miminashi commented on app/cm-update-7seg.service
> +Description=co2mon beacon sending service
ありがとうございます！

2020-09-12 00:09 UTC, merged